name: PincerEssentials
version: '1.0'
main: me.pincer.pincerEssentials.PincerEssentials
api-version: '1.21'
commands:
  gma:
    usage: /gma
    permission: gamemode.adventure
  gmsp:
    usage: /gmsp
    permission: gamemode.spectator
  gmc:
    usage: /gmc
    permission: gamemode.creative
  gms:
    usage: /gms
    permission: gamemode.survival
  god:
    usage: /god
    permission: essentials.godmode
  fix:
    usage: /fix
    permission: essentials.fix
  trash:
    usage: /trash
    permission: essentials.trash
  openinv:
    usage: /openinv [player]
    permission: essentials.openinv
  openender:
    usage: /openender [player]
    permission: essentials.openender
  tpa:
    usage: /tpa [player]
    permission: essentials.tpa
  tpahere:
    usage: /tpahere [player]
    permission: essentials.tpahere
  tpaccept:
    usage: /tpaccept
    permission: essentials.tpaccept
  tpdeny:
    usage: /tpdeny
    permission: essentials.tpdeny
  tp:
    usage: /tp [target] or /tp [player1] [player2]
    permission: essentials.tp
  tphere:
    usage: /tphere [player]
    permission: essentials.tphere
  back:
    usage: /back
    permission: essentials.back
  sethome:
    usage: /sethome
    permission: essentials.sethome
  home:
    usage: /home
    permission: essentials.home
  setwarp:
    usage: /setwarp <name>
    permission: essentials.setwarp
  warp:
    usage: /warp <name>
    permission: essentials.warp
  delwarp:
    usage: /delwarp <name>
    permission: essentials.delwarp
  spawn:
    usage: /spawn
    permission: essentials.spawn
